# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "kalilinux/rolling"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
   config.vm.synced_folder "./share", "/vagrant_data"
  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = false
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "4096"
   end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y rlwrap
     apt-get install -y seclists
     apt-get install -y gobuster
     apt-get install -y hydra
     apt-get install -y enum4linux
     apt-get install -y powershell-empire
     apt-get install -y odat
     apt-get install -y strongswan
     apt-get install -y seclists curl enum4linux feroxbuster impacket-scripts nbtscan nikto nmap onesixtyone oscanner redis-tools smbclient smbmap snmp sslscan sipvicious tnscmd10g whatweb wkhtmltopdf

     pip3 install git+https://github.com/Tib3rius/AutoRecon.git
     pip3 install impacket
     pip3 install kerbrute
     pip3 install bloodhound
     pip3 install droopescan

     gem install evil-winrm

     cd /opt
     chmod -R 755 /opt
     chown -R vagrant:vagrant /opt
     mkdir pspy
     wget https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy32
     wget https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy64
     mv pspy32 pspy64 pspy/
     git clone https://github.com/Tib3rius/privilege-escalation-awesome-scripts-suite.git 
     git clone https://github.com/mzet-/linux-exploit-suggester.git 
     git clone https://github.com/gladiatx0r/Powerless.git
     git clone https://github.com/PowerShellMafia/PowerSploit.git 
     git clone https://github.com/rasta-mouse/Sherlock.git 
     git clone https://github.com/AonCyberLabs/Windows-Exploit-Suggester.git 
     git clone https://github.com/SecWiki/windows-kernel-exploits.git 
     git clone https://github.com/BloodHoundAD/BloodHound.git
     git clone https://github.com/samratashok/nishang.git
     git clone https://github.com/ohpe/juicy-potato.git
     git clone https://github.com/int0x33/nc.exe.git 
     git clone https://github.com/21y4d/nmapAutomator.git
     ln -s $(pwd)/nmapAutomator/nmapAutomator.sh /usr/local/bin/
     wget https://github.com/RustScan/RustScan/releases/download/2.0.1/rustscan_2.0.1_amd64.deb
     dpkg -i rustscan_2.0.1_amd64.deb
     rm rustscan_2.0.1_amd64.deb
     wget https://github.com/ohpe/juicy-potato/releases/download/v0.1/JuicyPotato.exe
     mv JuicyPotato.exe juicy-potato/

     cd /usr/share/wordlists/
     gzip -d /usr/share/wordlists/rockyou.txt.gz

     updatedb

SHELL
end
